"""Section 15 canonical Pydantic schemas — the cross-component data contract.

Per the consolidation spec, every component reads/writes objects that conform to
the schemas in Section 15. This package is the single source of truth for those
schemas. Components import from here rather than re-declaring locally.

The package coexists with the pre-consolidation models in `artha.investor`,
`artha.portfolio`, and `artha.decision` — no existing code is broken. New
writers populate canonical objects; legacy readers continue against existing
ORM rows. Subsequent passes migrate the boundary.

Modules:

  * investor       — InvestorContextProfile (15.3.1)
  * case           — CaseObject (15.3.2)
  * mandate        — MandateObject + MandateAmendmentRequest (15.4)
  * model_portfolio — ModelPortfolioObject (15.5.1)
  * l4_manifest    — FundUniverseL4Entry + L4ManifestVersion (15.5.2/3)
  * holding        — Holding + slice/look_through/cascade/ingestion/conflict (15.3.3/4)
"""

from artha.canonical.agent_envelope import (
    AgentActivationEnvelope,
    ClarificationDialog,
    M0Briefing,
)
from artha.canonical.case import (
    CaseChannel,
    CaseObject,
    CaseStatus,
    DominantLens,
    LensMetadata,
    ProposedAction,
)
from artha.canonical.curated_knowledge import (
    CuratedKnowledgeSnapshot,
    DematMechanicsRule,
    DematMechanicsRulesSet,
    GiftCityRoutingRequirement,
    GiftCityRoutingRule,
    GiftCityRoutingRulesSet,
    HoldingPeriodCategory,
    RegulatoryChangelog,
    RegulatoryChangelogEntry,
    ResidencyStatus,
    SebiProductRule,
    SebiProductRulesSet,
    StructureCompatibilityMatrix,
    StructureCompatibilityRow,
    StructureCompatibilityVerdict,
    TaxRateRow,
    TaxTable,
)
from artha.canonical.evidence_verdict import (
    BehaviouralHistorySummary,
    CascadeAssessment,
    ConfidenceBandLabel,
    E1DimensionVerdict,
    E1Verdict,
    E2PortfolioQualityVerdict,
    E2SectorEvaluation,
    E2Verdict,
    E3Verdict,
    E4Verdict,
    E5HoldingEvaluation,
    E5Verdict,
    E6Verdict,
    FiveForcesScore,
    FundRiskScore,
    FundRiskScores,
    IndustryLifecycleStage,
    LiquidityManagerOutput,
    MacroDimension,
    MoatClassification,
    NormalisedReturns,
    RegimeAssessment,
    StandardEvidenceVerdict,
    SuitabilityCondition,
    TaxYearProjection,
    WatchCandidate,
)
from artha.canonical.holding import (
    CascadeCertainty,
    CascadeEvent,
    CascadeEventType,
    ConflictReport,
    ConflictType,
    Holding,
    IngestionReport,
    LookThroughEntry,
    LookThroughResponse,
    SliceResponse,
)
from artha.canonical.investor import (
    BeneficiaryMetadata,
    DataSource,
    DormantAdvisoryFraming,
    DormantBlindSpot,
    DormantI0Layer,
    DormantLayerStub,
    DormantLifeSituationPattern,
    DormantPatternInteractionFlag,
    DormantResistanceFlag,
    DormantStructuralComplicationPattern,
    DormantWealthOriginPattern,
    DormantWorldviewIndicator,
    FamilyMemberOverride,
    IntermediaryMetadata,
    InvestorContextProfile,
)
from artha.canonical.l4_manifest import (
    CascadeImpactSummary,
    FeeSchedule,
    FundUniverseL4Entry,
    L4ManifestChange,
    L4ManifestVersion,
    L4Operation,
    L4Status,
    LookThroughFrequency,
    RedemptionMechanics,
)
from artha.canonical.m0_briefer import (
    BriefingTrigger,
    M0BrieferInput,
    M0BrieferMetadata,
    M0BrieferOutput,
)
from artha.canonical.m0_indian_context import (
    IndianContextQueryType,
    M0IndianContextClientContext,
    M0IndianContextProductContext,
    M0IndianContextQuery,
    M0IndianContextResponse,
    RegulatoryRouting,
    StructuralCompatibility,
    TaxTreatment,
)
from artha.canonical.m0_portfolio_state import (
    M0PortfolioStateQuery,
    M0PortfolioStateQueryCategory,
    M0PortfolioStateResponse,
)
from artha.canonical.m0_router import (
    M0RouterClassification,
    M0RouterInput,
    M0RouterOutput,
)
from artha.canonical.mandate import (
    AssetClassLimits,
    ConcentrationLimits,
    FamilyMemberOverrideMandate,
    LiquidityWindow,
    MandateAmendmentRequest,
    MandateAmendmentStatus,
    MandateAmendmentType,
    MandateObject,
    SignoffEvidence,
    SignoffMethod,
    SubAssetClassLimits,
    VehicleLimits,
)
from artha.canonical.model_portfolio import (
    ConstructionContext,
    CounterfactualSupport,
    ExpectedReturnProfile,
    ModelPortfolioObject,
    ShadowModeRollout,
    TargetWithTolerance,
)
from artha.canonical.views import (
    AdvisorCaseDetailView,
    AdvisorPerClientView,
    BucketDriftRow,
    CIOConstructionApprovalView,
    CIOFirmDriftDashboard,
    CaseRecentRow,
    CellChangeSummary,
    ComplianceCaseReasoningTrail,
    ComplianceOverrideHistoryView,
    DriftStatusLight,
    EvidenceVerdictSummary,
    HoldingSummaryRow,
    N0InboxItem,
    OverrideHistoryRow,
    ReasoningTrailEntry,
    RedactionDecision,
    Role,
    ViewerContext,
)
from artha.canonical.cascade import (
    BucketRemappingEvent,
    L4CascadeCase,
    L4CascadeCaseStatus,
    L4CascadeRun,
    MandateAmendmentDiff,
    MandateAmendmentResult,
    MandateDiffField,
)
from artha.canonical.construction import (
    BlastRadius,
    BucketConstructionProposal,
    BucketVersionDiff,
    CellChange,
    ClientPortfolioSlice,
    ConstructionInputs,
    ConstructionRun,
    ConstructionRunStatus,
    ConstructionTrigger,
    L4SubstitutionImpact,
    RolloutMode,
    SingleClientConstructionProposal,
)
from artha.canonical.onboarding import (
    C0CheckpointExtraction,
    C0OnboardingTranscriptInput,
    ConfirmationMethod,
    MandateIntakePayload,
    OnboardingActivationStatus,
    OnboardingApiPayload,
    OnboardingCheckpoint,
    OnboardingCheckpointKind,
    OnboardingConflictItem,
    OnboardingFormPayload,
    OnboardingResult,
)
from artha.canonical.channels import (
    AlertClosureMetadata,
    AlertDeliveryState,
    AlertEngagementEvent,
    AlertEngagementType,
    C0AmbiguityType,
    C0ChannelSource,
    C0ExtractedEntities,
    C0ParseOutput,
    C0SessionMetadata,
    LibrarianSession,
    LibrarianTurn,
    PendingAmbiguity,
    PendingFollowup,
)
from artha.canonical.monitoring import (
    EX1Event,
    ExceptionCategory,
    ExceptionSeverity,
    M1Breach,
    M1BreachType,
    M1DriftReport,
    N0Alert,
    N0AlertCategory,
    N0Originator,
    PM1BenchmarkDivergenceDetail,
    PM1DriftDetail,
    PM1Event,
    PM1EventType,
    PM1ThesisValidityDetail,
    PM1ThresholdBreachDetail,
    RoutingDecision,
    T2CalibrationCurve,
    T2Finding,
    T2FindingCategory,
    T2FindingSeverity,
    T2PromptUpdateProposal,
    T2ReflectionRun,
    T2RuleUpdateProposal,
    T2RunStatus,
    T2RunType,
    ThesisValidityStatus,
    WatchMetadata,
)
from artha.canonical.governance import (
    A1Challenge,
    AccountabilityFlag,
    AccountabilityFlagType,
    AlternativeProposal,
    ChallengePoint,
    ChallengeSeverity,
    ChallengeType,
    ConstraintEvaluation,
    ConstraintEvaluationStatus,
    ConstraintType,
    G1Evaluation,
    G2Evaluation,
    G3Evaluation,
    OverrideRequirements,
    RegulatoryRuleEvaluation,
    RegulatoryRuleSeverity,
    RegulatoryRuleStatus,
    StressTestScenario,
)
from artha.canonical.synthesis import (
    AmplificationAssessment,
    CommitteePosition,
    ConflictArea,
    ConsensusBlock,
    CounterfactualFraming,
    DissentPoint,
    IC1Deliberation,
    IC1SubRole,
    MaterialityGateBlock,
    RenderedArtifact,
    RenderingDecision,
    S1Synthesis,
    SubRoleContribution,
)
from artha.canonical.portfolio_analytics import (
    AifVintageEntry,
    AnalyticsQueryInput,
    AnalyticsQueryResult,
    CashflowEntryAnalytics,
    ConcentrationMetrics,
    DeploymentMetrics,
    FeeBreakdown,
    FeeMetrics,
    LiquidityBucket,
    LiquidityMetrics,
    MetricCategory,
    MetricFlags,
    PeriodReturn,
    ProfitabilityMetrics,
    ReturnsMetrics,
    TaxMetrics,
    TopNConcentration,
    VintageMetrics,
)

__all__ = [
    # agent envelope (Section 9.2)
    "AgentActivationEnvelope",
    "ClarificationDialog",
    "M0Briefing",
    # case
    "CaseChannel",
    "CaseObject",
    "CaseStatus",
    "DominantLens",
    "LensMetadata",
    "ProposedAction",
    # m0 router (Section 15.6.1/2)
    "M0RouterClassification",
    "M0RouterInput",
    "M0RouterOutput",
    # m0 portfolio state (Section 15.6.3)
    "M0PortfolioStateQuery",
    "M0PortfolioStateQueryCategory",
    "M0PortfolioStateResponse",
    # evidence verdicts (Section 15.7)
    "BehaviouralHistorySummary",
    "CascadeAssessment",
    "ConfidenceBandLabel",
    "E1DimensionVerdict",
    "E1Verdict",
    "E2PortfolioQualityVerdict",
    "E2SectorEvaluation",
    "E2Verdict",
    "E3Verdict",
    "E4Verdict",
    "E5HoldingEvaluation",
    "E5Verdict",
    "E6Verdict",
    "FiveForcesScore",
    "FundRiskScore",
    "FundRiskScores",
    "IndustryLifecycleStage",
    "LiquidityManagerOutput",
    "MacroDimension",
    "MoatClassification",
    "NormalisedReturns",
    "RegimeAssessment",
    "StandardEvidenceVerdict",
    "SuitabilityCondition",
    "TaxYearProjection",
    "WatchCandidate",
    # holding
    "CascadeCertainty",
    "CascadeEvent",
    "CascadeEventType",
    "ConflictReport",
    "ConflictType",
    "Holding",
    "IngestionReport",
    "LookThroughEntry",
    "LookThroughResponse",
    "SliceResponse",
    # curated knowledge (Section 8.5.2)
    "CuratedKnowledgeSnapshot",
    "DematMechanicsRule",
    "DematMechanicsRulesSet",
    "GiftCityRoutingRequirement",
    "GiftCityRoutingRule",
    "GiftCityRoutingRulesSet",
    "HoldingPeriodCategory",
    "RegulatoryChangelog",
    "RegulatoryChangelogEntry",
    "ResidencyStatus",
    "SebiProductRule",
    "SebiProductRulesSet",
    "StructureCompatibilityMatrix",
    "StructureCompatibilityRow",
    "StructureCompatibilityVerdict",
    "TaxRateRow",
    "TaxTable",
    # investor
    "BeneficiaryMetadata",
    "DataSource",
    "DormantAdvisoryFraming",
    "DormantBlindSpot",
    "DormantI0Layer",
    "DormantLayerStub",
    "DormantLifeSituationPattern",
    "DormantPatternInteractionFlag",
    "DormantResistanceFlag",
    "DormantStructuralComplicationPattern",
    "DormantWealthOriginPattern",
    "DormantWorldviewIndicator",
    "FamilyMemberOverride",
    "IntermediaryMetadata",
    "InvestorContextProfile",
    # m0 briefer (Section 15.6.7)
    "BriefingTrigger",
    "M0BrieferInput",
    "M0BrieferMetadata",
    "M0BrieferOutput",
    # m0 indian context (Section 15.6.4)
    "IndianContextQueryType",
    "M0IndianContextClientContext",
    "M0IndianContextProductContext",
    "M0IndianContextQuery",
    "M0IndianContextResponse",
    "RegulatoryRouting",
    "StructuralCompatibility",
    "TaxTreatment",
    # l4 manifest
    "CascadeImpactSummary",
    "FeeSchedule",
    "FundUniverseL4Entry",
    "L4ManifestChange",
    "L4ManifestVersion",
    "L4Operation",
    "L4Status",
    "LookThroughFrequency",
    "RedemptionMechanics",
    # mandate
    "AssetClassLimits",
    "ConcentrationLimits",
    "FamilyMemberOverrideMandate",
    "LiquidityWindow",
    "MandateAmendmentRequest",
    "MandateAmendmentStatus",
    "MandateAmendmentType",
    "MandateObject",
    "SignoffEvidence",
    "SignoffMethod",
    "SubAssetClassLimits",
    "VehicleLimits",
    # model portfolio
    "ConstructionContext",
    "CounterfactualSupport",
    "ExpectedReturnProfile",
    "ModelPortfolioObject",
    "ShadowModeRollout",
    "TargetWithTolerance",
    # views by role (Section 14)
    "AdvisorCaseDetailView",
    "AdvisorPerClientView",
    "BucketDriftRow",
    "CIOConstructionApprovalView",
    "CIOFirmDriftDashboard",
    "CaseRecentRow",
    "CellChangeSummary",
    "ComplianceCaseReasoningTrail",
    "ComplianceOverrideHistoryView",
    "DriftStatusLight",
    "EvidenceVerdictSummary",
    "HoldingSummaryRow",
    "N0InboxItem",
    "OverrideHistoryRow",
    "ReasoningTrailEntry",
    "RedactionDecision",
    "Role",
    "ViewerContext",
    # cascade workflows (Section 5.9.3 + 7.6)
    "BucketRemappingEvent",
    "L4CascadeCase",
    "L4CascadeCaseStatus",
    "L4CascadeRun",
    "MandateAmendmentDiff",
    "MandateAmendmentResult",
    "MandateDiffField",
    # construction pipeline (Section 4.2 + 5.8)
    "BlastRadius",
    "BucketConstructionProposal",
    "BucketVersionDiff",
    "CellChange",
    "ClientPortfolioSlice",
    "ConstructionInputs",
    "ConstructionRun",
    "ConstructionRunStatus",
    "ConstructionTrigger",
    "L4SubstitutionImpact",
    "RolloutMode",
    "SingleClientConstructionProposal",
    # onboarding (Section 10.3)
    "C0CheckpointExtraction",
    "C0OnboardingTranscriptInput",
    "ConfirmationMethod",
    "MandateIntakePayload",
    "OnboardingActivationStatus",
    "OnboardingApiPayload",
    "OnboardingCheckpoint",
    "OnboardingCheckpointKind",
    "OnboardingConflictItem",
    "OnboardingFormPayload",
    "OnboardingResult",
    # channels (Section 15.6.1 + 15.6.6 + 15.12.1)
    "AlertClosureMetadata",
    "AlertDeliveryState",
    "AlertEngagementEvent",
    "AlertEngagementType",
    "C0AmbiguityType",
    "C0ChannelSource",
    "C0ExtractedEntities",
    "C0ParseOutput",
    "C0SessionMetadata",
    "LibrarianSession",
    "LibrarianTurn",
    "PendingAmbiguity",
    "PendingFollowup",
    # monitoring + reflection (Section 15.10–15.12)
    "EX1Event",
    "ExceptionCategory",
    "ExceptionSeverity",
    "M1Breach",
    "M1BreachType",
    "M1DriftReport",
    "N0Alert",
    "N0AlertCategory",
    "N0Originator",
    "PM1BenchmarkDivergenceDetail",
    "PM1DriftDetail",
    "PM1Event",
    "PM1EventType",
    "PM1ThesisValidityDetail",
    "PM1ThresholdBreachDetail",
    "RoutingDecision",
    "T2CalibrationCurve",
    "T2Finding",
    "T2FindingCategory",
    "T2FindingSeverity",
    "T2PromptUpdateProposal",
    "T2ReflectionRun",
    "T2RuleUpdateProposal",
    "T2RunStatus",
    "T2RunType",
    "ThesisValidityStatus",
    "WatchMetadata",
    # governance + accountability (Section 15.9)
    "A1Challenge",
    "AccountabilityFlag",
    "AccountabilityFlagType",
    "AlternativeProposal",
    "ChallengePoint",
    "ChallengeSeverity",
    "ChallengeType",
    "ConstraintEvaluation",
    "ConstraintEvaluationStatus",
    "ConstraintType",
    "G1Evaluation",
    "G2Evaluation",
    "G3Evaluation",
    "OverrideRequirements",
    "RegulatoryRuleEvaluation",
    "RegulatoryRuleSeverity",
    "RegulatoryRuleStatus",
    "StressTestScenario",
    # synthesis layer (Section 15.8)
    "AmplificationAssessment",
    "CommitteePosition",
    "ConflictArea",
    "ConsensusBlock",
    "CounterfactualFraming",
    "DissentPoint",
    "IC1Deliberation",
    "IC1SubRole",
    "MaterialityGateBlock",
    "RenderedArtifact",
    "RenderingDecision",
    "S1Synthesis",
    "SubRoleContribution",
    # portfolio analytics
    "AifVintageEntry",
    "AnalyticsQueryInput",
    "AnalyticsQueryResult",
    "CashflowEntryAnalytics",
    "ConcentrationMetrics",
    "DeploymentMetrics",
    "FeeBreakdown",
    "FeeMetrics",
    "LiquidityBucket",
    "LiquidityMetrics",
    "MetricCategory",
    "MetricFlags",
    "PeriodReturn",
    "ProfitabilityMetrics",
    "ReturnsMetrics",
    "TaxMetrics",
    "TopNConcentration",
    "VintageMetrics",
]
