"""Alembic env script for Samriddhi AI.

Loads `Base.metadata` from `artha.common.db.base` so autogenerated
migrations track every ORM model registered in the codebase. The DB URL
is read from the `ARTHA_DATABASE_URL` env var when present, falling back
to the value in `alembic.ini` (SQLite for local dev).

Usage:
  * `alembic revision --autogenerate -m "add foo"` — generate a migration
    by diffing the current DB schema against the live `Base.metadata`.
  * `alembic upgrade head` — apply outstanding migrations.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Import Base + all ORM modules so Base.metadata is fully populated.
from artha.common.db.base import Base  # noqa: F401

# Importing the package side-effect registers every ORM table with `Base`.
import artha.accountability.t1.orm  # noqa: F401
import artha.channels.orm  # noqa: F401
import artha.m0.librarian_orm  # noqa: F401

config = context.config

# Override the DB URL from env if present.
if (env_url := os.environ.get("ARTHA_DATABASE_URL")) is not None:
    config.set_main_option("sqlalchemy.url", env_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live engine."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
